/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PracticaHTTP;

//import javax.swing.text.Document;
import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class App {

    public static void main(String[] args) throws IOException{
        String direccionPagina = "https://en.wikipedia.org";
        Document doc;

        //Estableciendo conexion usando Jsoup
        doc = Jsoup.connect(direccionPagina).get();
        System.out.println(doc.title());

        //Busco parrafos y demás componentes
        Elements parrafos = doc.select("p");
        System.out.println("La cantidad de párrafos en esta página es: " + parrafos.size());
        

        //Titulo de la pagina
        // String title = doc.title();
        // System.out.println("Titulo: "+ title);

        //Links en la pagina
        // Elements links = doc.select("a[href]");
        // for (Element link : links) {
        //     System.out.println("\nLink: " + link.attr("href"));
        //     System.out.println("Text: " + link.text());
        // }

    }

}
